### ISSUE TITLE
Unable to play any somafm station

### ISSUE THREAD

**Issue by P0CA** [AlexandrePTJ/mopidy-somafm#26]
Hi, I have recently reinstalled mopidy V2 on a Rasbian Jessie. I can browse the somafm stations but can't play any. When I try to add one on the playlist via MusicBox nothing happens. Running mopidy in verbose mode, I got the following trace: 

```
 DEBUG    2016-04-22 17:19:13,343 [24567:HttpServer] mopidy.http.handlers
  Received WebSocket message from 192.168.1.12: u'{"method":"core.tracklist.add","params":{"at_position":1,"uris":["http://somafm.com/bagel.pls"]},"jsonrpc":"2.0","id":229}'
DEBUG    2016-04-22 17:19:13,391 [24567:StreamBackend-7] mopidy.stream.actor
  Unwrapping stream from URI: http://somafm.com/bagel.pls
DEBUG    2016-04-22 17:19:15,154 [24567:StreamBackend-7] mopidy.stream.actor
  GStreamer failed scanning URI (http://somafm.com/bagel.pls): gst-stream-error-quark: This appears to be a text file (5)
DEBUG    2016-04-22 17:19:15,839 [24567:StreamBackend-7] mopidy.stream.actor
  Parsed playlist (http://somafm.com/bagel.pls) and found new URI: http://ice1.somafm.com/bagel-128-mp3
DEBUG    2016-04-22 17:19:15,842 [24567:StreamBackend-7] mopidy.stream.actor
  Unwrapping stream from URI: http://ice1.somafm.com/bagel-128-mp3
DEBUG    2016-04-22 17:19:16,481 [24567:StreamBackend-7] mopidy.stream.actor
  Unwrapped potential None stream: http://ice1.somafm.com/bagel-128-mp3
ERROR    2016-04-22 17:19:16,499 [24567:Core-16] mopidy.core.library
  StreamBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 19, in _backend_error_handling
    yield
  File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 236, in lookup
    result = future.get()
  File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/dist-packages/mopidy/stream/actor.py", line 69, in lookup
    uri=uri, length=scan_result.duration)
  File "/usr/lib/python2.7/dist-packages/mopidy/models/immutable.py", line 214, in replace
    other = super(ValidatedImmutableObject, self).replace(**kwargs)
  File "/usr/lib/python2.7/dist-packages/mopidy/models/immutable.py", line 116, in replace
    other._set_field(key, value)
  File "/usr/lib/python2.7/dist-packages/mopidy/models/immutable.py", line 186, in _set_field
    object.__setattr__(self, name, value)
  File "/usr/lib/python2.7/dist-packages/mopidy/models/fields.py", line 50, in __set__
    value = self.validate(value)
  File "/usr/lib/python2.7/dist-packages/mopidy/models/fields.py", line 131, in validate
    (self._name, self._min, value))
ValueError: Expected length to be at least 0, not -1

```

I tried with different format and quality, same results.
Same results too if I add the URLs given by [http://somafm.com/bagel/directstreamlinks.html](url) directly in thre Streams backend.

**Comment by hk3wx** [comment]
I have the same problem ¬¬

**Comment by AlexandrePTJ** [comment]
Mopidy is only supported with Python version greater than 3.7. Here version is 2.7.
