### ISSUE TITLE
ValueError: substring not found

### ISSUE THREAD

**Issue by morithil** [AlexandrePTJ/mopidy-somafm#40]
Hey, I'm getting this error in the latest build:
 
 File "/usr/lib/python3/dist-packages/mopidy_somafm/backend.py", line 52, in lookup
channel_name = uri[uri.index("/") + 1 :]
ValueError: substring not found

**Comment by AlexandrePTJ** [comment]
Cannot you tell me how to reproduce this and your python version ?

**Comment by morithil** [comment]
Apologies @AlexandrePTJ , I will try to dedicate some time to looking at this in the next week or so.

Can you confirm that images from SomaFM are loading for you correctly using the Mopidy-iris frontend?

**Comment by TrollDecker** [comment]
Heyo, I seem to be seeing a similar error message:

```
Feb 07 15:54:18 pirate-audio mopidy[470]: ERROR    [Core-9] mopidy.core.library SomaFMBackend backend caused an exception.
Feb 07 15:54:18 pirate-audio mopidy[470]: Traceback (most recent call last):
Feb 07 15:54:18 pirate-audio mopidy[470]:   File "/usr/lib/python3/dist-packages/mopidy/core/library.py", line 17, in _backend_error_handling
Feb 07 15:54:18 pirate-audio mopidy[470]:     yield
Feb 07 15:54:18 pirate-audio mopidy[470]:   File "/usr/lib/python3/dist-packages/mopidy/core/library.py", line 217, in lookup
Feb 07 15:54:18 pirate-audio mopidy[470]:     result = future.get()
Feb 07 15:54:18 pirate-audio mopidy[470]:   File "/usr/lib/python3/dist-packages/pykka/_threading.py", line 45, in get
Feb 07 15:54:18 pirate-audio mopidy[470]:     _compat.reraise(*self._data['exc_info'])
Feb 07 15:54:18 pirate-audio mopidy[470]:   File "/usr/lib/python3/dist-packages/pykka/_compat/__init__.py", line 29, in reraise
Feb 07 15:54:18 pirate-audio mopidy[470]:     raise value
Feb 07 15:54:18 pirate-audio mopidy[470]:   File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 193, in _actor_loop
Feb 07 15:54:18 pirate-audio mopidy[470]:     response = self._handle_receive(envelope.message)
Feb 07 15:54:18 pirate-audio mopidy[470]:   File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 299, in _handle_receive
Feb 07 15:54:18 pirate-audio mopidy[470]:     return callee(*message.args, **message.kwargs)
Feb 07 15:54:18 pirate-audio mopidy[470]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_somafm/backend.py", line 53, in lookup
Feb 07 15:54:18 pirate-audio mopidy[470]:     channel_name = uri[uri.index("/") + 1 :]
Feb 07 15:54:18 pirate-audio mopidy[470]: ValueError: substring not found
```

Initially I thought this was why the stream wasn't playing at all before it dawned on me to install `gstreamer-plugins-bad` (D'oh!). Since then, this error still appears, but the stream plays and updates its metadata without problem.

My setup is a couple-day old fresh install, so everything is as up-to-date as I can get it.
* Python 3.7.3
* Mopidy 3.1.1
* Mopidy-SomaFM 2.0.1

Steps to reproduce:
* Click Browse > SomaFM
* Double-click any station or click the station's menu button (the three dots) and click play.

**Comment by morithil** [comment]
Thanks @TrollDecker - everything you've got there is exactly what I'm experiencing too

**Comment by tetricky** [comment]
Exactly the same here. Clean install. raspberry pi.  The only (marginal) difference is that I have:
```
[somafm]
enabled = true
encoding = aac
quality = highest
dj_as_artist = true
```
```
Feb 09 18:58:03 pi-mopidy-snap mopidy[417]: ERROR    [Core-11] mopidy.core.library SomaFMBackend backend caused an exception.
Feb 09 18:58:03 pi-mopidy-snap mopidy[417]: Traceback (most recent call last):
Feb 09 18:58:03 pi-mopidy-snap mopidy[417]:   File "/usr/lib/python3/dist-packages/mopidy/core/library.py", line 17, in _backend_error_handling
Feb 09 18:58:03 pi-mopidy-snap mopidy[417]:     yield
Feb 09 18:58:03 pi-mopidy-snap mopidy[417]:   File "/usr/lib/python3/dist-packages/mopidy/core/library.py", line 181, in get_images
Feb 09 18:58:03 pi-mopidy-snap mopidy[417]:     if future.get() is None:
Feb 09 18:58:03 pi-mopidy-snap mopidy[417]:   File "/usr/lib/python3/dist-packages/pykka/_threading.py", line 45, in get
Feb 09 18:58:03 pi-mopidy-snap mopidy[417]:     _compat.reraise(*self._data['exc_info'])
Feb 09 18:58:03 pi-mopidy-snap mopidy[417]:   File "/usr/lib/python3/dist-packages/pykka/_compat/__init__.py", line 29, in reraise
Feb 09 18:58:03 pi-mopidy-snap mopidy[417]:     raise value
Feb 09 18:58:03 pi-mopidy-snap mopidy[417]:   File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 193, in _actor_loop
Feb 09 18:58:03 pi-mopidy-snap mopidy[417]:     response = self._handle_receive(envelope.message)
Feb 09 18:58:03 pi-mopidy-snap mopidy[417]:   File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 299, in _handle_receive
Feb 09 18:58:03 pi-mopidy-snap mopidy[417]:     return callee(*message.args, **message.kwargs)
Feb 09 18:58:03 pi-mopidy-snap mopidy[417]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_somafm/backend.py", line 103, in get_images
Feb 09 18:58:03 pi-mopidy-snap mopidy[417]:     channel_name = uri[uri.index("/") + 1 :]
Feb 09 18:58:03 pi-mopidy-snap mopidy[417]: ValueError: substring not found
```

**Comment by tetricky** [comment]
could this be a mopidy core/library issue? I have also seen a bunch of errors in other modules....for example iTunesPodcastBackend
```
Feb 09 19:12:42 pi-mopidy-snap mopidy[416]: ERROR    [Core-11] mopidy.core.library iTunesPodcastBackend backend caused an exception.
Feb 09 19:12:42 pi-mopidy-snap mopidy[416]: Traceback (most recent call last):
Feb 09 19:12:42 pi-mopidy-snap mopidy[416]:   File "/usr/lib/python3/dist-packages/mopidy/core/library.py", line 17, in _backend_error_handling
Feb 09 19:12:42 pi-mopidy-snap mopidy[416]:     yield
Feb 09 19:12:42 pi-mopidy-snap mopidy[416]:   File "/usr/lib/python3/dist-packages/mopidy/core/library.py", line 217, in lookup
Feb 09 19:12:42 pi-mopidy-snap mopidy[416]:     result = future.get()
Feb 09 19:12:42 pi-mopidy-snap mopidy[416]:   File "/usr/lib/python3/dist-packages/pykka/_threading.py", line 45, in get
Feb 09 19:12:42 pi-mopidy-snap mopidy[416]:     _compat.reraise(*self._data['exc_info'])
Feb 09 19:12:42 pi-mopidy-snap mopidy[416]:   File "/usr/lib/python3/dist-packages/pykka/_compat/__init__.py", line 29, in reraise
Feb 09 19:12:42 pi-mopidy-snap mopidy[416]:     raise value
Feb 09 19:12:42 pi-mopidy-snap mopidy[416]:   File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 193, in _actor_loop
Feb 09 19:12:42 pi-mopidy-snap mopidy[416]:     response = self._handle_receive(envelope.message)
Feb 09 19:12:42 pi-mopidy-snap mopidy[416]:   File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 299, in _handle_receive
Feb 09 19:12:42 pi-mopidy-snap mopidy[416]:     return callee(*message.args, **message.kwargs)
Feb 09 19:12:42 pi-mopidy-snap mopidy[416]:   File "/usr/lib/python3/dist-packages/mopidy/backend.py", line 131, in lookup
Feb 09 19:12:42 pi-mopidy-snap mopidy[416]:     raise NotImplementedError
Feb 09 19:12:42 pi-mopidy-snap mopidy[416]: NotImplementedError
```

**Comment by TrollDecker** [comment]
That seems to be unrelated, if I'm reading that right. 😕

Also, you can wrap your logs and configs in code tags to make them easier to read. Just stick ``` on separate lines around them. 🙂

**Comment by AlexandrePTJ** [comment]
Tested with Muse and MusicBox interface and images are back.
Don't know why Iris do not display them.

**Comment by TrollDecker** [comment]
Is Iris somehow the cause of the `Substring not found` error? 🤔

**Comment by AlexandrePTJ** [comment]
No it was not. It was a real bug in this extension code.

**Comment by TrollDecker** [comment]
Ah, right. I've only just now noticed the commit reference in the "issue closed" message. Whoops. 😅

**Comment by tatealive** [comment]
Thanks @AlexandrePTJ  !

However after upgrading to 2.0.2 and restarting the system, I am getting the following error:
```
File "/usr/lib/python3/dist-packages/mopidy_somafm/backend.py", line 52, in lookup
mopidy[660]:     channel_name = uri[uri.index("/") + 1 :]
mopidy[660]: ValueError: substring not found
```

**Comment by TrollDecker** [comment]
It's not producing that error for me after I updated, so it sounds like your Mopidy is still finding an older version of the plugin? 😕 

Have you double-checked with `pip list`?

**Comment by tatealive** [comment]
Yep, have confirmed 2.0.2 in pip listOn 11 Feb 2021 6:54 am, Jo Decker <notifications@github.com> wrote:

It's not producing that error for me after I updated, so it sounds like your Mopidy is still finding an older version of the plugin? 😕

Have you double-checked with pip list ?

**Comment by TrollDecker** [comment]
Have you tried `apt remove mopidy-somafm` to make sure there isn't an apt-installed copy sitting around taking precedence?

Failing that, did you remember to use `sudo` in all cases?

**Comment by tatealive** [comment]
Removed APT copy, that was the issue thanks @TrollDecker 

New error message now related to the images, I'll make a new bug report
